---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhanpf.
--- DateTime: 2018/4/25 10:55
---

local fate = {
    name = "Fate_Testarrosa",
    age = 19,
    skill = "Lightning Blade"
}

print(fate)