---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhanpf.
--- DateTime: 2018/4/25 10:54
---

local lumi = {
    name = "Nanoha_Takamachi",
    age = 19,
    skill = "Starlight Breaker"
}

print(lumi)